/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;

/**
 *
 * @author Weptz
 */
public class InterfazCliente extends javax.swing.JFrame {

    /**
     * Creates new form InterfazCliente
     */
    
    private ControladorCliente controlador;
    

    public InterfazCliente() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        this.setSize(550, 550);
        
        
        
        this.panelPrincipal.setVisible(true);
        this.panelIniciarSesion.setVisible(false);
        this.panelRegistrarse.setVisible(false);
        this.panelNoRegistrarse.setVisible(false);
        this.panelMenu.setVisible(false);
        this.panelPrincipalClienteReg.setVisible(false);
        this.panelPedidosAnte.setVisible(false);
    }
    
    public void setControlador(ControladorCliente controlador) {

        this.controlador = controlador;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelBase = new javax.swing.JPanel();
        panelPrincipal = new javax.swing.JPanel();
        botonRegistrarse = new javax.swing.JButton();
        BotonNoRegistrarse = new javax.swing.JButton();
        botonVolverInterClient = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonIniciarSesion = new javax.swing.JButton();
        panelIniciarSesion = new javax.swing.JPanel();
        LabelIniciarSesion = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        emailField = new javax.swing.JTextField();
        botonInicS = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botonVolverInicS = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelRegistrarse = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nombreRegField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ApellidoRegField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        emailRegField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        contraseniaRegField = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        tarjetaField = new javax.swing.JTextField();
        botonVolverReg = new javax.swing.JButton();
        botonRegReg = new javax.swing.JButton();
        panelPrincipalClienteReg = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        labelNombreClienteReg = new javax.swing.JLabel();
        botonRealizarPedClienteReg = new javax.swing.JButton();
        botonVerPedidos = new javax.swing.JButton();
        botonVolverClienteReg = new javax.swing.JButton();
        panelPedidosAnte = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPedidosRecurrentes = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        botonVolverPedidosAnteriores = new javax.swing.JButton();
        botonRepetirPedido = new javax.swing.JButton();
        panelNoRegistrarse = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        emailNoRegis = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        nombreNoRegis = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        botonVolverNoRegis = new javax.swing.JButton();
        botonEntrarNoRegis = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        apellidosNoregis = new javax.swing.JTextField();
        panelMenu = new javax.swing.JPanel();
        botonAniadir = new javax.swing.JButton();
        botonRealizarPedido = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        etiquetaPrecioTotal = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tablaCesta = new javax.swing.JTable();
        botonEliminar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMenu = new javax.swing.JTable();
        botonVolverMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        PanelBase.setBackground(new java.awt.Color(204, 204, 204));
        PanelBase.setLayout(new javax.swing.BoxLayout(PanelBase, javax.swing.BoxLayout.LINE_AXIS));

        panelPrincipal.setBackground(new java.awt.Color(201, 40, 79));

        botonRegistrarse.setBackground(new java.awt.Color(255, 227, 131));
        botonRegistrarse.setText("Registrarse ");
        botonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarseActionPerformed(evt);
            }
        });

        BotonNoRegistrarse.setBackground(new java.awt.Color(255, 227, 131));
        BotonNoRegistrarse.setText("No Registrarse");
        BotonNoRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNoRegistrarseActionPerformed(evt);
            }
        });

        botonVolverInterClient.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverInterClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInterClientActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 227, 131));
        jLabel1.setText("CLIENTES ");

        botonIniciarSesion.setBackground(new java.awt.Color(255, 227, 131));
        botonIniciarSesion.setText("Iniciar Sesion");
        botonIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIniciarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1))
                    .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolverInterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonNoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(163, 163, 163))
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(botonIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(BotonNoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(botonVolverInterClient, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(287, Short.MAX_VALUE))
        );

        PanelBase.add(panelPrincipal);

        panelIniciarSesion.setBackground(new java.awt.Color(201, 40, 79));

        LabelIniciarSesion.setBackground(new java.awt.Color(255, 227, 131));
        LabelIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LabelIniciarSesion.setForeground(new java.awt.Color(255, 227, 131));
        LabelIniciarSesion.setText("INICIAR SESIÓN");

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        botonInicS.setBackground(new java.awt.Color(255, 227, 131));
        botonInicS.setText("Iniciar Sesón");
        botonInicS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicSActionPerformed(evt);
            }
        });

        botonVolverInicS.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverInicS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverInicSActionPerformed(evt);
            }
        });

        jLabel6.setText("Correo Electronico");

        jLabel7.setText("Contraseña");

        javax.swing.GroupLayout panelIniciarSesionLayout = new javax.swing.GroupLayout(panelIniciarSesion);
        panelIniciarSesion.setLayout(panelIniciarSesionLayout);
        panelIniciarSesionLayout.setHorizontalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIniciarSesionLayout.createSequentialGroup()
                        .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelIniciarSesion)
                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonInicS, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(25, 25, 25))
                    .addComponent(botonVolverInicS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        panelIniciarSesionLayout.setVerticalGroup(
            panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIniciarSesionLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(LabelIniciarSesion)
                .addGap(39, 39, 39)
                .addGroup(panelIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIniciarSesionLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelIniciarSesionLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(botonInicS)))
                .addGap(31, 31, 31)
                .addComponent(botonVolverInicS, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(310, Short.MAX_VALUE))
        );

        PanelBase.add(panelIniciarSesion);

        panelRegistrarse.setBackground(new java.awt.Color(201, 40, 79));
        panelRegistrarse.setForeground(new java.awt.Color(153, 255, 204));

        jLabel2.setBackground(new java.awt.Color(255, 227, 131));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 227, 131));
        jLabel2.setText("REGISTRARSE");

        jLabel5.setText("Nombre");

        jLabel8.setText("Apellido");

        jLabel9.setText("Correo Electronico");

        jLabel10.setText("Contraseña");

        jLabel11.setText("Numero de tarjeta");

        botonVolverReg.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverReg.setToolTipText("");
        botonVolverReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverRegActionPerformed(evt);
            }
        });

        botonRegReg.setBackground(new java.awt.Color(255, 227, 131));
        botonRegReg.setText("Registrarse");

        javax.swing.GroupLayout panelRegistrarseLayout = new javax.swing.GroupLayout(panelRegistrarse);
        panelRegistrarse.setLayout(panelRegistrarseLayout);
        panelRegistrarseLayout.setHorizontalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel2))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ApellidoRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseniaRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelRegistrarseLayout.createSequentialGroup()
                                    .addComponent(botonVolverReg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(botonRegReg))
                                .addComponent(tarjetaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        panelRegistrarseLayout.setVerticalGroup(
            panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRegistrarseLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(30, 30, 30)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidoRegField, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseniaRegField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tarjetaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(botonVolverReg, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRegistrarseLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(botonRegReg)))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        PanelBase.add(panelRegistrarse);

        panelPrincipalClienteReg.setBackground(new java.awt.Color(201, 40, 79));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 227, 131));
        jLabel17.setText("Bienvenido");

        labelNombreClienteReg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        botonRealizarPedClienteReg.setBackground(new java.awt.Color(255, 227, 131));
        botonRealizarPedClienteReg.setText("Realizar Pedido");

        botonVerPedidos.setBackground(new java.awt.Color(255, 227, 131));
        botonVerPedidos.setText("Pedidos anteriores");
        botonVerPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerPedidosActionPerformed(evt);
            }
        });

        botonVolverClienteReg.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverClienteReg.setText("volver");
        botonVolverClienteReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverClienteRegActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPrincipalClienteRegLayout = new javax.swing.GroupLayout(panelPrincipalClienteReg);
        panelPrincipalClienteReg.setLayout(panelPrincipalClienteRegLayout);
        panelPrincipalClienteRegLayout.setHorizontalGroup(
            panelPrincipalClienteRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalClienteRegLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(botonVolverClienteReg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalClienteRegLayout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(panelPrincipalClienteRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(botonRealizarPedClienteReg, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelPrincipalClienteRegLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(labelNombreClienteReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(149, 149, 149))
        );
        panelPrincipalClienteRegLayout.setVerticalGroup(
            panelPrincipalClienteRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalClienteRegLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(labelNombreClienteReg, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(botonRealizarPedClienteReg, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botonVerPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(botonVolverClienteReg)
                .addContainerGap(294, Short.MAX_VALUE))
        );

        PanelBase.add(panelPrincipalClienteReg);

        panelPedidosAnte.setBackground(new java.awt.Color(201, 40, 79));

        tablaPedidosRecurrentes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Precio", "Fecha", "Hora", "Menu"
            }
        ));
        jScrollPane2.setViewportView(tablaPedidosRecurrentes);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 227, 131));
        jLabel18.setText("Pedidos anteriores");

        botonVolverPedidosAnteriores.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverPedidosAnteriores.setText("Volver");
        botonVolverPedidosAnteriores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverPedidosAnterioresActionPerformed(evt);
            }
        });

        botonRepetirPedido.setBackground(new java.awt.Color(255, 227, 131));
        botonRepetirPedido.setText("Repetir pedido");
        botonRepetirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRepetirPedidoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPedidosAnteLayout = new javax.swing.GroupLayout(panelPedidosAnte);
        panelPedidosAnte.setLayout(panelPedidosAnteLayout);
        panelPedidosAnteLayout.setHorizontalGroup(
            panelPedidosAnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidosAnteLayout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidosAnteLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(botonVolverPedidosAnteriores)
                .addGap(60, 60, 60)
                .addComponent(jLabel18)
                .addGap(58, 58, 58)
                .addComponent(botonRepetirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPedidosAnteLayout.setVerticalGroup(
            panelPedidosAnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidosAnteLayout.createSequentialGroup()
                .addContainerGap(160, Short.MAX_VALUE)
                .addGroup(panelPedidosAnteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolverPedidosAnteriores)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRepetirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        PanelBase.add(panelPedidosAnte);

        panelNoRegistrarse.setBackground(new java.awt.Color(201, 40, 79));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 227, 131));
        jLabel12.setText("Usuario sin registrar");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Correo electronico");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Nombre");

        botonVolverNoRegis.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverNoRegis.setText("Volver");
        botonVolverNoRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverNoRegisActionPerformed(evt);
            }
        });

        botonEntrarNoRegis.setBackground(new java.awt.Color(255, 227, 131));
        botonEntrarNoRegis.setText("Entrar");
        botonEntrarNoRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarNoRegisActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel15.setText("Apellidos");

        javax.swing.GroupLayout panelNoRegistrarseLayout = new javax.swing.GroupLayout(panelNoRegistrarse);
        panelNoRegistrarse.setLayout(panelNoRegistrarseLayout);
        panelNoRegistrarseLayout.setHorizontalGroup(
            panelNoRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                .addGroup(panelNoRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(panelNoRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(emailNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidosNoregis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonEntrarNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(botonVolverNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNoRegistrarseLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(228, 228, 228))
        );
        panelNoRegistrarseLayout.setVerticalGroup(
            panelNoRegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNoRegistrarseLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel12)
                .addGap(32, 32, 32)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(emailNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreNoRegis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidosNoregis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botonEntrarNoRegis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonVolverNoRegis)
                .addContainerGap(321, Short.MAX_VALUE))
        );

        PanelBase.add(panelNoRegistrarse);

        panelMenu.setBackground(new java.awt.Color(201, 40, 79));

        botonAniadir.setBackground(new java.awt.Color(255, 227, 131));
        botonAniadir.setText("Añadir");
        botonAniadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAniadirActionPerformed(evt);
            }
        });

        botonRealizarPedido.setBackground(new java.awt.Color(255, 227, 131));
        botonRealizarPedido.setText("Realizar Pedido");
        botonRealizarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarPedidoActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 227, 131));
        jLabel19.setText("Menu");

        etiquetaPrecioTotal.setBackground(new java.awt.Color(102, 102, 102));
        etiquetaPrecioTotal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        etiquetaPrecioTotal.setText("Total: 0");
        etiquetaPrecioTotal.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 102, 102)));

        tablaCesta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tablaCesta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tablaCesta);

        botonEliminar.setBackground(new java.awt.Color(255, 227, 131));
        botonEliminar.setText("Eliminar");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 227, 131));
        jLabel21.setText("Cesta");

        tablaMenu.setBackground(new java.awt.Color(102, 102, 102));
        tablaMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tablaMenu.setForeground(new java.awt.Color(51, 51, 51));
        tablaMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Menu", "Tapa", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tablaMenu);

        botonVolverMenu.setBackground(new java.awt.Color(255, 227, 131));
        botonVolverMenu.setText("jButton1");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addComponent(etiquetaPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(botonRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(62, 62, 62))))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addComponent(botonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(botonRealizarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMenuLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(etiquetaPrecioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAniadir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVolverMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );

        PanelBase.add(panelMenu);

        jPanel1.add(PanelBase, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 233, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverInicSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInicSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverInicSActionPerformed

    private void botonInicSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonInicSActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void botonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarseActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_botonRegistrarseActionPerformed

    private void botonIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIniciarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIniciarSesionActionPerformed

    private void BotonNoRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNoRegistrarseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonNoRegistrarseActionPerformed

    private void botonVolverRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverRegActionPerformed

    private void botonVolverNoRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverNoRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverNoRegisActionPerformed

    private void botonEntrarNoRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarNoRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEntrarNoRegisActionPerformed

    private void botonVolverInterClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverInterClientActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverInterClientActionPerformed

    private void botonAniadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAniadirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAniadirActionPerformed

    private void botonVolverClienteRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverClienteRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverClienteRegActionPerformed

    private void botonVolverPedidosAnterioresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverPedidosAnterioresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVolverPedidosAnterioresActionPerformed

    private void botonVerPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerPedidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerPedidosActionPerformed

    private void botonRepetirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRepetirPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRepetirPedidoActionPerformed

    private void botonRealizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonRealizarPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazCliente().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField ApellidoRegField;
    public javax.swing.JButton BotonNoRegistrarse;
    private javax.swing.JLabel LabelIniciarSesion;
    public javax.swing.JPanel PanelBase;
    public javax.swing.JTextField apellidosNoregis;
    public javax.swing.JButton botonAniadir;
    public javax.swing.JButton botonEliminar;
    public javax.swing.JButton botonEntrarNoRegis;
    public javax.swing.JButton botonInicS;
    public javax.swing.JButton botonIniciarSesion;
    public javax.swing.JButton botonRealizarPedClienteReg;
    public javax.swing.JButton botonRealizarPedido;
    public javax.swing.JButton botonRegReg;
    public javax.swing.JButton botonRegistrarse;
    public javax.swing.JButton botonRepetirPedido;
    public javax.swing.JButton botonVerPedidos;
    public javax.swing.JButton botonVolverClienteReg;
    public javax.swing.JButton botonVolverInicS;
    public javax.swing.JButton botonVolverInterClient;
    public javax.swing.JButton botonVolverMenu;
    public javax.swing.JButton botonVolverNoRegis;
    public javax.swing.JButton botonVolverPedidosAnteriores;
    public javax.swing.JButton botonVolverReg;
    public javax.swing.JPasswordField contraseniaRegField;
    public javax.swing.JTextField emailField;
    public javax.swing.JTextField emailNoRegis;
    public javax.swing.JTextField emailRegField;
    public javax.swing.JLabel etiquetaPrecioTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JLabel labelNombreClienteReg;
    public javax.swing.JTextField nombreNoRegis;
    public javax.swing.JTextField nombreRegField;
    public javax.swing.JPanel panelIniciarSesion;
    public javax.swing.JPanel panelMenu;
    public javax.swing.JPanel panelNoRegistrarse;
    public javax.swing.JPanel panelPedidosAnte;
    public javax.swing.JPanel panelPrincipal;
    public javax.swing.JPanel panelPrincipalClienteReg;
    public javax.swing.JPanel panelRegistrarse;
    public javax.swing.JPasswordField passwordField;
    public javax.swing.JTable tablaCesta;
    public javax.swing.JTable tablaMenu;
    public javax.swing.JTable tablaPedidosRecurrentes;
    public javax.swing.JTextField tarjetaField;
    // End of variables declaration//GEN-END:variables
}
